# Generated by Django 2.0.2 on 2019-10-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=10000)),
                ('phone_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subname', models.CharField(max_length=255)),
                ('priceDollar', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('priceRs', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('manual', models.FileField(blank=True, null=True, upload_to='')),
                ('discount', models.DecimalField(decimal_places=2, default=5.0, max_digits=20)),
                ('min_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_series', to='racerfly.Category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_items', to='racerfly.Series'),
        ),
        migrations.AddField(
            model_name='customer',
            name='carts',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice_users', to='racerfly.Item'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice_users_fav', to='racerfly.Item'),
        ),
    ]
