# Generated by Django 2.0.2 on 2019-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
