# Generated by Django 2.0.2 on 2019-10-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0002_auto_20191017_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemToBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('delievered_at', models.CharField(max_length=255)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_itemstobuy', to='racerfly.Item')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice_users', to='racerfly.ItemToBuy'),
        ),
    ]
