# Generated by Django 2.0.2 on 2019-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0003_auto_20191028_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
