# Generated by Django 2.0.2 on 2019-10-28 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0004_itemtobuy_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 21, 53, 13, 754183)),
        ),
    ]
