# Generated by Django 2.0.2 on 2019-11-10 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0009_auto_20191103_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtobuy',
            old_name='delievered_at',
            new_name='delievery_at',
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 23, 39, 30, 272699)),
        ),
    ]
