# Generated by Django 2.0.2 on 2019-11-10 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0010_auto_20191110_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_orders', to='racerfly.Customer'),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 23, 42, 38, 596329)),
        ),
    ]
