# Generated by Django 2.0.2 on 2019-11-10 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0011_auto_20191110_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 0, 52, 29, 444139)),
        ),
    ]
