# Generated by Django 2.0.2 on 2019-11-30 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0014_auto_20191130_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Util',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 14, 13, 16, 819956)),
        ),
    ]
