# Generated by Django 2.0.2 on 2019-12-02 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0015_auto_20191130_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='order_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 20, 45, 13, 655005)),
        ),
    ]
