# Generated by Django 2.0.2 on 2019-12-02 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0016_auto_20191202_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='track',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 22, 47, 24, 44669)),
        ),
    ]
