# Generated by Django 2.0.2 on 2019-12-05 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0017_auto_20191202_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 17, 5, 29, 184984)),
        ),
    ]
