# Generated by Django 2.0.2 on 2019-12-12 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0019_auto_20191206_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 13, 8, 1, 399320)),
        ),
    ]
