# Generated by Django 2.0.2 on 2019-12-12 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0020_auto_20191212_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('suggested_on', models.DateTimeField(default=datetime.datetime(2019, 12, 12, 14, 21, 44, 979729))),
            ],
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 14, 21, 44, 945186)),
        ),
    ]
