# Generated by Django 2.1.7 on 2019-12-13 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0022_auto_20191212_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 18, 39, 5, 497491)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 18, 39, 5, 513115)),
        ),
    ]
