# Generated by Django 2.1.7 on 2019-12-13 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0023_auto_20191213_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 18, 52, 22, 667645)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 18, 52, 22, 683265)),
        ),
    ]
