# Generated by Django 2.1.7 on 2019-12-13 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0024_auto_20191213_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 19, 13, 31, 312945)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 19, 13, 31, 318929)),
        ),
    ]
