# Generated by Django 2.1.7 on 2019-12-14 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0026_auto_20191215_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 0, 53, 51, 853336)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 0, 53, 51, 853336)),
        ),
    ]
