# Generated by Django 2.0.2 on 2019-12-16 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0027_auto_20191215_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 18, 23, 26, 921644)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 18, 23, 26, 941594)),
        ),
    ]
