# Generated by Django 2.0.2 on 2020-02-12 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0028_auto_20191216_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('discount', models.FloatField(default=20.0)),
                ('maxdiscount', models.FloatField(default=4000.0)),
            ],
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 5, 11, 19, 875243)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 5, 11, 19, 879884)),
        ),
    ]
