# Generated by Django 2.0.2 on 2020-02-12 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerfly', '0029_auto_20200212_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 5, 37, 12, 602035)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 5, 37, 12, 606616)),
        ),
    ]
